baseURL = "https://sh1n00.com"
title = "sh1n00's portfolio"
theme = "hugo-coder"
languageCode = "ja"
defaultContentLanguage = "ja"
paginate = 20
enableEmoji = true
# Enable Disqus comments
disqusShortname = "yourdiscussshortname"
googleAnalytics = 'G-YC6EG4Q1ZX'


[markup.highlight]
style = "github-dark"

[params]
author = "sh1n00"
description = "sh1n00's portfolio"
keywords = "developer,personal"
info = ["バックエンドエンジニア"]
avatarURL = "images/icon.jpg"
# TODO faviconの設定
# favicon_32 = "/img/favicon.png"
# favicon_16 = "/img/favicon.png"

since = 2023

# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = true
# Series see also post count
maxSeeAlsoItems = 5

# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
# outboundLinksTracking = true
# fileDownloadsTracking = true

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
[params.googleTagManager]
id = "G-YC6EG4Q1ZX"

# If you want to use Yandex Metrika(https://metrika.yandex.ru) for analytics, add this section
# [params.yandexMetrika]
# id = "gid"

# If you want to use Application Insights(https://azure.com/) for analytics, add this section
# [params.applicationInsights]
# connectionString = "connectionString"

# If you want to use microanalytics.io for analytics, add this section
# [params.microAnalytics]
# id = "ABCDE"
# dnt = "false" # respect DNT tracker, "true" by default

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/sh1n00/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/Shinori0425"

[languages.ja]
languageName = ":us:"
title = "sh1n00's portfolio"

[[languages.ja.menu.main]]
name = "ブログ"
weight = 1
url = "posts/"

[[languages.ja.menu.main]]
name = "経歴"
weight = 2
url = "career/"

[[languages.ja.menu.main]]
name = "連絡"
weight = 3
url = "contact/"

[[languages.ja.menu.main]]
name = "カテゴリー"
weight = 4
url = "categories/"

[[languages.ja.menu.main]]
name = "タグ"
weight = 5
url = "tags/"

[languages.en]
languageName = ":jp:"
title = "sh1n00's portfolio"

[languages.en.params]
author = "sh1n00"
info = "engineer"
description = ""
keywords = ""

[[languages.en.menu.main]]
name = "Career"
weight = 1
url = "career/"

[[languages.en.menu.main]]
name = "Contact"
weight = 2
url = "contact/"